# Generated by Django 5.1.3 on 2024-12-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_currency_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencypair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
