# Generated by Django 5.1.3 on 2024-12-02 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_currencypair'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypair',
            name='base_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='base_currency', to='currency.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencypair',
            name='quote_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quote_currency', to='currency.currency'),
            preserve_default=False,
        ),
    ]
