# Generated by Django 5.1.3 on 2024-12-02 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_exchangerate_currency_pair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencypair',
            old_name='currency_pair',
            new_name='pair_code',
        ),
    ]
